import type { LucidePackage } from './types.js'

export const SERVER_NAME = 'lucide-icons-mcp-server'
export const SERVER_VERSION = '0.1.0'

export const LUCIDE_DOCS_BASE = 'https://lucide.dev'
export const LUCIDE_API_BASE = 'https://lucide.dev/api'
export const LUCIDE_REPO = 'https://github.com/lucide-icons/lucide'
export const LUCIDE_ICONS_BASE = `${LUCIDE_DOCS_BASE}/icons`

export const MAX_SEARCH_RESULTS = 20

export const CATEGORIES = [
  'accessibility',
  'account',
  'animals',
  'arrows',
  'brands',
  'buildings',
  'charts',
  'communication',
  'connectivity',
  'cursors',
  'design',
  'development',
  'devices',
  'emoji',
  'files',
  'finance',
  'food-beverage',
  'gaming',
  'home',
  'layout',
  'mail',
  'math',
  'medical',
  'multimedia',
  'nature',
  'navigation',
  'notifications',
  'people',
  'photography',
  'science',
  'seasons',
  'security',
  'shapes',
  'shopping',
  'social',
  'sports',
  'sustainability',
  'text',
  'time',
  'tools',
  'transportation',
  'travel',
  'weather',
] as const

export type IconCategory = (typeof CATEGORIES)[number]

export const PACKAGES: LucidePackage[] = [
  {
    id: 'lucide',
    name: 'Lucide',
    npmPackage: 'lucide',
    framework: 'Vanilla JS',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide`,
    installCmd: 'npm install lucide',
    codeLanguage: 'js',
  },
  {
    id: 'lucide-react',
    name: 'Lucide React',
    npmPackage: 'lucide-react',
    framework: 'React',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-react`,
    installCmd: 'npm install lucide-react',
    codeLanguage: 'jsx',
  },
  {
    id: 'lucide-vue-next',
    name: 'Lucide Vue Next',
    npmPackage: 'lucide-vue-next',
    framework: 'Vue 3',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-vue-next`,
    installCmd: 'npm install lucide-vue-next',
    codeLanguage: 'vue',
  },
  {
    id: 'lucide-angular',
    name: 'Lucide Angular',
    npmPackage: 'lucide-angular',
    framework: 'Angular',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-angular`,
    installCmd: 'npm install lucide-angular',
    codeLanguage: 'ts',
  },
  {
    id: 'lucide-svelte',
    name: 'Lucide Svelte',
    npmPackage: '@lucide/svelte',
    framework: 'Svelte 5',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-svelte`,
    installCmd: 'npm install @lucide/svelte',
    codeLanguage: 'svelte',
  },
  {
    id: 'lucide-svelte-4',
    name: 'Lucide Svelte (v4)',
    npmPackage: 'lucide-svelte',
    framework: 'Svelte 4',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-svelte`,
    installCmd: 'npm install lucide-svelte',
    codeLanguage: 'svelte',
  },
  {
    id: 'lucide-solid',
    name: 'Lucide Solid',
    npmPackage: 'lucide-solid',
    framework: 'SolidJS',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-solid`,
    installCmd: 'npm install lucide-solid',
    codeLanguage: 'jsx',
  },
  {
    id: 'lucide-preact',
    name: 'Lucide Preact',
    npmPackage: 'lucide-preact',
    framework: 'Preact',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-preact`,
    installCmd: 'npm install lucide-preact',
    codeLanguage: 'jsx',
  },
  {
    id: 'lucide-react-native',
    name: 'Lucide React Native',
    npmPackage: 'lucide-react-native',
    framework: 'React Native',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-react-native`,
    installCmd: 'npm install lucide-react-native',
    codeLanguage: 'jsx',
  },
  {
    id: 'lucide-static',
    name: 'Lucide Static',
    npmPackage: 'lucide-static',
    framework: 'Static/CSS',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-static`,
    installCmd: 'npm install lucide-static',
    codeLanguage: 'html',
  },
  {
    id: 'lucide-astro',
    name: 'Lucide Astro',
    npmPackage: '@lucide/astro',
    framework: 'Astro',
    docsUrl: `${LUCIDE_DOCS_BASE}/guide/packages/lucide-astro`,
    installCmd: 'npm install @lucide/astro',
    codeLanguage: 'astro',
  },
]
